spring: 
  jpa: 
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  #    设置json显示的格式化
    jackson: 
      serialization: true

flowable:
  async-executor-activate: false
