# Redis数据库索引（默认为0）
spring: 
 redis: 
  database: 0
# Redis服务器地址
  host: 118.89.112.68
# Redis服务器连接端口
  port: 33000
# Redis服务器连接密码（默认为空）
  password: libra@Bmsoft_V19
# 连接池最大连接数（使用负值表示没有限制）
# 连接超时时间（毫秒）
  timeout: 3000
  jedis: 
   pool: 
    maxTotal: 8
# 连接池最大阻塞等待时间（使用负值表示没有限制）
    maxWait: 10000ms
# 连接池中的最大空闲连接
    maxIdle: 8
# 连接池中的最小空闲连接
    minIdle: 1
#    当池内没有可用连接时，最大等待时间
    maxWaitMillis: 10000
